### ISSUE TITLE
Crashes on Windows if CIRCUITPY is read-only

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-install-update-tool#3]
```
Traceback (most recent call last):
  File "run.py", line 397, in <module>
  File "run.py", line 378, in main
  File "run.py", line 100, in delete_folders_in_lib
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 622, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
PermissionError: [WinError 19] The media is write protected: 'E:\\lib\\adafruit_bus_device\\i2c_device.mpy'
```

**Comment by dmcomm** [comment]
793030d
